app.route("/users/:id")
.get(function(req,res)
{
  User.findOne({id:req.params.id},function(err,foundUser)
{
  if(foundUser)
  {
  res.send(foundUser);
  }
  else{
    res.send("No user matching with this id");
  }
});
})
.put(function(req,res)
  {
  User.update(
      {id:req.params.id},
      {id:req.body.id,
        firstname:req.body.firstname,
      lastname:req.body.lastname,
    mail_id:req.body.mail_id,
      password:req.body.password},
  {overwrite:true},
      function(err)
      {
        if(!err)
        {
          res.send("Successfully Updated users");
        }
        else(err)
        {
          console.log(err);
        }
      }
    );
  })
  .patch(function(req,res)
{
  User.update({id:req.params.id},{$set:req.body},function(err)
{
  if(!err)
  {
    res.send("Successfully Updated Users")
  }
  else{
    console.log(err);
  }
});
})
.delete(function(req,res)
{
  User.deleteOne(
    {id:req.params.id},
    function(err)
    {
      if(!err)
      {
        res.send("Successfully deleted the User")
      }
      else{
        console.log("err");
      }
    }
  )
});
